### ISSUE TITLE
Atualizar capa/visual do manual

### ISSUE THREAD

**Issue by isadorasophia** [LSchanner/Manual-do-Bixo#7]
Procurarei atualizar a identidade visual do manual (é claro, mantendo a mesma essência dos anos anteriores), com uma possível arte para a capa.

**Comment by isadorasophia** [comment]
Ok, acabei de terminar. Vocês dão uma olhada e vê se curtiram, se tem algo errado, sei lá. Eu segui o modelo dos anos anteriores, de qualquer forma.

**Comment by LSchanner** [comment]
Eu curti a arte mas achei que a imagem gerada talvez esteja um pouco pequena. É difícil prever como vai ficar depois de impresso. É trivial gerar um arquivo com uma resolução maior?

**Comment by isadorasophia** [comment]
Então, se você quiser eu posso aumentar, mas eu peguei a mesma resolução das capas passadas (exatamente do tamanho de uma folha A4), por isso eu imaginei que estaria ok.

**Comment by LSchanner** [comment]
Eu não manjo,  eu vi comparando o tamanho dos arquivos, que eu sei que não
é uma boa métrica. Ainda assim, se não custa nada, acho válido colocar uma
resolução maior.

**Comment by isadorasophia** [comment]
Eu dei uma olhada nas configurações da geração de pdf, alterei algumas
coisas mas nada que tenha mudado significativamente.
Aparentemente, a versão de 2013 é mega big resolution - e eu fiz a versão
de 2015 seguindo os parâmetros da de 2014. Como o produto final vai ser
folha A4, eu acho que não vai dar problema porque tá tudo configurado
exatamente pra uma folha A4 (a qualidade deve ficar igualzinho a de 2014).
No caso, se vocês acharem que a resolução de 2014 é meio meh eu posso dar
uma ajeitada (é que eu teria que basicamente refazer todo o design pra uma
resolução bigger :P).

Em 4 de janeiro de 2015 13:56, Lucas Silva Schanner <
notifications@github.com> escreveu:

> Eu não manjo, eu vi comparando o tamanho dos arquivos, que eu sei que não
> é uma boa métrica. Ainda assim, se não custa nada, acho válido colocar uma
> resolução maior.
>

**Comment by isadorasophia** [comment]
Ok done, arrumei a resolução. Aparentemente apesar do pdf estar pra 300dpi
a imagem tava em 72dpi (durt) então não adiantava nada. O melhor que
consegui foi pra 150dpi por conta do desenho, mas melhorou bastante, acho
que a capa não fica pixelizada agora.

Em 4 de janeiro de 2015 15:55, Isadora Sophia <isaecia@gmail.com> escreveu:
